### ISSUE TITLE
ORCA does not save itself automatically

### ISSUE THREAD

**Issue by fbdescamps** [snoplus/orca#233] opened 2017-01-06 20:15 UTC
We need it to save:
 * at the start of each run
 * every 5min

It was checked that ORCA does not currently save to file at the run start in this shift:
http://snopl.us/shift/view/b6886d7d0e9a4a92a4040242d0225698

**Comment by fbdescamps** [comment] 2017-01-06 20:34
@BenLand100 pointed out that this might be because of the fact that we use our own run control...

**Comment by BenLand100** [comment] 2017-01-06 21:38
That does look to be the case - see this line in the orca run control
https://github.com/snoplus/orca/blob/252a0bac2025b8d0bfd7cd3cc6fec6635a1181ae/Source/Objects/Control/RunControl/ORRunController.m#L666
which seems to be missing an analogous statement in our run control
https://github.com/snoplus/orca/blob/986b1630d03c4603be38c6714eb707903dab2210/Source/Experiments/SNOP/SNOPController.m#L411

**Comment by fbdescamps** [comment] 2017-01-11 00:36
@jcaravaca Any update on this?

**Comment by fbdescamps** [comment] 2017-01-16 20:04
@jcaravaca I think the latest here was that ORCA only saves to the current open file at run-start when the GUI actually changed. Has this been confirmed, and does ORCA indeed save at all types of run-starts when the GUI has changed? If so, please close this issue.

We will not be automatically saving every 5minutes or so due to the following arguments that were made against:
 * Experts sometimes use the unsaved state to be able to recover from changes that need to be reversed. This is a handy thing to keep for now.
 * If it done every run.. then you know the state. As in: ORCA crashes.. I wonder if that last change I  made was saved or not? That question is much easier if the save happens only at run boundaries.

**Comment by tlatorre-uchicago** [comment] 2017-01-18 00:33
Confirmed that ORCA does not save the .Orca file when you start a run from the SNO+ control panel.

**Comment by fbdescamps** [comment] 2017-01-18 00:35
Did you change something in the GUI before the run start?

**Comment by tlatorre-uchicago** [comment] 2017-01-18 00:36
Yes, we changed the PED -> PULGT button in the MTC GUI.

**Comment by tlatorre-uchicago** [comment] 2017-01-20 23:58
Fixed in #258.

**Closed by tlatorre-uchicago** 2017-01-20 23:58 UTC
Labels: Critical
