### ISSUE TITLE
ORCA wouldn't save or load new test run after switching into expert mode

### ISSUE THREAD

**Issue by pershint** [snoplus/orca#249] opened 2017-01-18 06:57 UTC
On the graveyard shift on Jan. 18, 2016, we noticed that PED was masked into the MAINTENANCE, DEFAULT run.  After consulting with Freija, we switched from operator mode to expert mode to change PED to PGT.

We decided to try changing PED to PGT and saving as a new test run type (test run DEFAULTNOPED under run name MAINTENANCE).  ORCA tried to save the run as DIAGNOSTIC - DEFAULTNOPED unsuccessfully, and we could not load DEFAULTNOPED (see below).

![screen shot 2017-01-18 at 1 52 28 am](https://cloud.githubusercontent.com/assets/7978480/22053829/2cc464dc-dd21-11e6-9462-8781b2c27081.png)

We then tried to overwrite MAINTENANCE - DEFAULT with all the default settings, except PED -> PGT.  Similar errors printed when trying to save MAINTENANCE DEFAULT and re-load it (see below).

![screen shot 2017-01-18 at 1 44 43 am](https://cloud.githubusercontent.com/assets/7978480/22053919/77f3e4dc-dd21-11e6-87ce-734e3d03c940.png)

**Comment by pershint** [comment] 2017-01-18 10:34
Eric told us that this issue is due to having empty fields (specifically, the 10MHz clk (31..0) and bits (56..32) fields in the MTC/D panel).  After putting in zeroes, the save feature works.

**Comment by marzece** [comment] 2017-01-18 12:13
For the record this will be solved in a some what more permanent manner in my forthcoming MTC changes. After that we shouldn't have to worry about those fields being blank and screwing things up. We can leave this issue open till then though so I can get more issue closing stats when I submit the PR.

**Comment by tlatorre-uchicago** [comment] 2017-01-23 06:09
Dupe of #152.

**Closed by tlatorre-uchicago** 2017-01-23 06:09 UTC
