### ISSUE TITLE
ORCA should default to locked mode on startup

### ISSUE THREAD

**Issue by mnirkko** [snoplus/orca#324] opened 2017-02-21 15:45 UTC
This UG shift, we restarted ORCA and were able to change expert settings from the start. Since we are 2 newly trained shifters +1 trainee, this should certainly not be possible.

Suggest defaulting to locked mode on startup.

**Comment by jcaravaca** [comment] 2017-02-21 17:20
Was the global security disabled or the panels unlocked? i.e. did you have re-enable security by closing the lock at Preferences->Security or just by closing individual panel locks?

**Comment by mnirkko** [comment] 2017-02-21 18:09
The security was globally disabled, we were able to change trigger 
settings, ramp up crates etc. (under expert guidance via telephone). We 
locked ORCA again using Preferences -> Security.

**Comment by jcaravaca** [comment] 2017-02-21 19:32
Then, this is because an expert saved the .Orca file after disabling the security, which shouldn't have happened.

**Comment by mnirkko** [comment] 2017-02-21 19:58
Well I would still call that a bug if the disabled security can be saved 
in the settings. ;)

**Comment by jcaravaca** [comment] 2017-02-21 20:02
Others would call it a feature :) The problem is that this is part of the core of the ORCA code, used be other experiments. So it might be hard to change. Essentially the global security should *never* be disabled during normal running.

**Comment by tlatorre-uchicago** [comment] 2017-03-13 19:48
Fixed in #331.

**Closed by tlatorre-uchicago** 2017-03-13 19:48 UTC
